---
- name: test_task2
  hosts: all
  become: yes
  vars:
    user1: "user"
    user1pass: "new_password"
    user2: "user2"
    user2pass: "password"

  tasks:
    - name: смена пароля
      user:
        name: "{{ user1 }}"
        password: "{{ user1pass | password_hash('sha512') }}"
        update_password: always

    - name: создание нового пользователя
      user:
        name: "{{ user2 }}"
        password: "{{ user2pass | password_hash('sha512') }}"
        append: yes
        shell: /bin/bash
        create_home: yes

    - name: изменение порта ssh
      shell: 
         cmd: sed -i 's/^#Port 22/Port 229/' /etc/ssh/sshd_config

    - name: restart sshd
      service:
        name: sshd
        state: restarted
